const nome= prompt("Nome completo: ")
console.log('Nome:',nome, typeof(nome))
const nasc=prompt("Data de nascimento: ")
console.log("Data nascimento ", nasc, typeof(nasc))
const end=prompt("Endereço: ")
console.log("Endereço",end, typeof(end))
const cpf=Number(prompt("CPF"))
console.log("CPF", cpf, typeof(cpf))
const escol=prompt("Escolaridade:")
console.log("Escolaridade", escol, typeof(escol))
const cnh=prompt("Possui CNH?")
console.log("CNH", cnh, typeof(cnh))
const filhos=Number(prompt("Quantos filhos possui?"))
console.log("Quantos filhos possui?", filhos, typeof(filhos))
const cargo=prompt("Cargo atual")
console.log("Cargo atual", cargo, typeof(cargo))
const sal=Number(prompt("Salario atual:"))
console.log("Salario: ", sal, typeof(sal))
const comis=prompt("Recebe comissão? Se sim, informe a porcentagem, caso não, responda com zero")
console.log("Comissão", comis, typeof(comis))
const admissao= Number(prompt("Informe o ano de admissão:"))
console.log("Ano admissão:", admissao, typeof(admissao))

console.log("-=-=-=-=--=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=")

console.log("Nome:",nome ,"Nascido(a) em:",nasc,"Residente em:",end,"Cadastrado sob cpf:",cpf,"Grau de instrução",escol,"CNH n",cnh,"N de filhos",filhos,"Atualmente ocupa o cargo de:",cargo,"Salario atual",sal,"Recebendo comição de ",comis,"Admitido no ano de:",admissao)